### PR TITLE
Add pidrusage

### PR DESCRIPTION
**Pull request by dalance**
I added pidrusage corresponding to proc_pid_rusage.
If file separating will be done first, I'll re-create another PR.

### CODE REVIEW

**Comment by andrewdavidmackenzie** [comment]
For such new functionality I'd prefer if you added in separate files.

When I have time I will go back and do the split on the previously added functionality.

**Comment by dalance** [comment]
OK. Thnaks.

**Comment by andrewdavidmackenzie** [comment]
Working on in https://github.com/andrewdavidmackenzie/libproc-rs/pull/22

So I will close this

**Comment by andrewdavidmackenzie** [comment]
BTW: would you want/like/mind being included in a list of contributors to the project?

**Pull request closed without merging**
